/* eslint-disable no-unused-vars */
const exbrowser = "safari";
// values: "chrome", "safari", "edge", "firefox", "opera", "yandex", "whale"
const linkredirectionoptions = "https://www.turnoffthelights.com/browser/extension/options/";
const linkcapturescreenshot = "https://www.turnoffthelights.com/browser/extension/capture-screenshot-of-video/";
const linkdeveloperwebsite = "https://www.turnoffthelights.com";
const linkproduct = "https://itunes.apple.com/app/id1273998507";
const linkdonate = "https://www.turnoffthelights.com/donate/";
const writereview = "https://itunes.apple.com/app/id1273998507?action=write-review";
const linkchangelog = "https://www.turnoffthelights.com/browser/extension/changelog/safari/";
const linktranslate = "https://www.turnoffthelights.com/browser/extension/translate/";
const linksupport = "https://www.turnoffthelights.com/support/";
const linkwelcome = "https://www.turnoffthelights.com/browser/extension/welcome/safari/";
const linkuninstall = "https://www.turnoffthelights.com/browser/extension/uninstall/safari/";
const linkguide = "https://www.turnoffthelights.com/browser/extension/guide/safari/";
const linkshare = "https://www.turnoffthelights.com/share/browser/extension/";
const linkbrowsertheme = "https://www.turnoffthelights.com/browser/theme/";
const browsernewtab = "safari://newtab/";
const browserstore = "https://apps.apple.com";
const linkyoutube = "https://www.youtube.com/c/turnoffthelights?sub_confirmation=1";
const linkauroraplayerapp = "https://www.stefanvd.net/project/aurora-player/";
const linktotlmobileapp = "https://www.turnoffthelights.com/mobile/";
const linkgamepad = "https://www.turnoffthelights.com/game-controller/";
const devmode = true;
const devdonate = false;
